export const cloudExplImages = {
  background: require('./images/iron-cloud-explorer-loaderbg.png'),
  tabMap: require('./images/iron-cloud-explorer-map.png'),
  mapWorld: require('./images/iron-cloud-explorer-mapworld.png'),
  tabTimeline: require('./images/iron-cloud-explorer-timeline.png'),
  tabQuiz: require('./images/iron-cloud-explorer-quiz.png'),
  tabArticles: require('./images/iron-cloud-explorer-articles.png'),
  tabFavorites: require('./images/iron-cloud-explorer-favorites.png'),
  tabSettings: require('./images/iron-cloud-explorer-settings.png'),
  onboardingHero1: require('./images/iron-cloud-explorer-onboardfirst.png'),
  onboardingHero2: require('./images/iron-cloud-explorer-onboardsecond.png'),
  onboardingHero3: require('./images/iron-cloud-explorer-onboardthird.png'),
  onboardingHero4: require('./images/iron-cloud-explorer-onboardfourth.png'),
  onboardingIconAnchor: require('./images/iron-cloud-explorer-onboardiconanchor.png'),
  onboardingIconSnowflake: require('./images/iron-cloud-explorer-onboardiconsnowflake.png'),
  onboardingIconGlobe: require('./images/iron-cloud-explorer-onboardiconglobe.png'),
  onboardingIconQuiz: require('./images/iron-cloud-explorer-onboardiconquiz.png'),
  quizIntro: require('./images/iron-cloud-explorer-quizintro.png'),
  quizResult: require('./images/iron-cloud-explorer-quizresult.png'),
  timelineEarlyConcepts: require('./images/iron-cloud-explorer-timeline-early-concepts.png'),
  favoritesEmpty: require('./images/iron-cloud-explorer-favorites-empty.png'),
  settingsHero: require('./images/iron-cloud-explorer-settings-hero.png'),
} as const;
