export const cloudExplImages = {
  background: require('./images/loaderbg.png'),
  tabMap: require('./images/map.png'),
  mapWorld: require('./images/mapworld.png'),
  tabTimeline: require('./images/timeline.png'),
  tabQuiz: require('./images/quiz.png'),
  tabArticles: require('./images/articles.png'),
  tabFavorites: require('./images/favorites.png'),
  tabSettings: require('./images/settings.png'),
  onboardingHero1: require('./images/onboardfirst.png'),
  onboardingHero2: require('./images/onboardsecond.png'),
  onboardingHero3: require('./images/onboardthird.png'),
  onboardingHero4: require('./images/onboardfourth.png'),
  onboardingIconAnchor: require('./images/onboardiconanchor.png'),
  onboardingIconSnowflake: require('./images/onboardiconsnowflake.png'),
  onboardingIconGlobe: require('./images/onboardiconglobe.png'),
  onboardingIconQuiz: require('./images/onboardiconquiz.png'),
  quizIntro: require('./images/quizintro.png'),
  quizResult: require('./images/quizresult.png'),
  timelineEarlyConcepts: require('./images/timelineEarlyConcepts.png'),
  favoritesEmpty: require('./images/favoritesEmpty.png'),
  settingsHero: require('./images/settingsHero.png'),
} as const;
